events {}

http {
    include /etc/nginx/mime.types;

    server {
        listen 80; # Ακούει στο κλασικό port του Web

        # 1. Όταν κάποιος ζητάει την αρχική σελίδα, δώσε του τη React
        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ /index.html;
        }

        # 2. Όταν το URL ξεκινάει από /api/, στείλ' το εσωτερικά στο Node container
        location /api/ {
            proxy_pass http://gamer_node_backend:5000; # Χρησιμοποιεί το όνομα του container!
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}